Add mobile view
vanja-stojanovic-quantox/pod-request-access-landing-page pull request #1
Opened 2021-09-28 07:16 UTC by vanja-stojanovic-quantox

2021-09-28 14:27 UTC, vmladenovic approved these changes
Gde ti je prettier i njegov config?

2021-09-29 19:58 UTC, vmladenovic requested changes
Vanja, potrebno je da instaliras prettier preko npm komande `npm i prettier` i da napravis konfiguracio fajl .prettierrc (mozes pitati na grupi da ti neko posalje svoj). Na kraju ce ti se generisati package.json gde mozes da dodas komandu za prettier (kako bi mogla da ga pokrenes sa `npm run naziv_komande_iz_package_fajla`
)

2021-09-29 19:58 UTC, vmladenovic commented on index.html
> +</html>
```suggestion
</html>

```

2021-09-30 07:09 UTC, vanja-stojanovic-quantox commented on index.html
> +</html>
Instalirala sam odmah kada Ste rekli jos proslog puta, samo sto nisam primetila da nisam lepo uradila. Mislim da je sada sve kako treba, uradila sam odmah kada sam videla komentar u ponedeljak, ali sam zaboravila da odgovorim. Izvinjavam se
Saljem uskoro ceo zadatak sa prettier-om.

2021-09-30 21:02 UTC, vmladenovic requested changes
Kada se instalira prettier preko `npm install prettier` generise se i package.json i package.lock koje takodje treba komitovati. Ako zatreba pomoc mozemo se cuti sutra

2021-09-30 21:02 UTC, vmladenovic commented on assets/css/.prettierrc
> +{}
```suggestion
{
    "arrowParens": "always",
    "bracketSpacing": false,
    "jsxBracketSameLine": true,
    "printWidth": 80,
    "proseWrap": "always",
    "semi": true,
    "singleQuote": true,
    "tabWidth": 4,
    "trailingComma": "all",
    "useTabs": false
}

```

2021-09-30 21:02 UTC, vmladenovic commented on assets/js/script.js
> +    $("#access-button").click(function () {
U JS-u cemo koristiti jednostruke navodnike
```suggestion
    $('#access-button').click(function () {
```

2021-09-30 21:02 UTC, vmladenovic commented on assets/js/script.js
> +    $("#access-button").click(function () {
Ovo treba primeniti na celi fajl

2021-09-30 21:02 UTC, vmladenovic commented on index.html
> +        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
Nismo se dogovorili da koristimo JQuery, trebalo je koristiti cist Vanilla JS

2021-09-30 21:02 UTC, vmladenovic commented on assets/js/script.js
> +}
```suggestion
}

```
Kada se pojavi crveni kruzic na kraju fajla (kao ovde) to znaci da ti fali jedan prazan red na kraju

2021-10-01 13:58 UTC, vanja-stojanovic-quantox commented on assets/js/script.js
> +}
Prepravila sam sve, nadam se da je sada dobro.

2021-10-02 07:26 UTC, vmladenovic reviewed
@vanja-stojanovic-quantox komitovala si node_modules a to nije trebalo. Takodje, node_modules  se nalazi unutar `assets/css/` a treba da bude u rootu(glavnom folderu projekta - pocetnom).Takodje i .prettierrc. Trebalo bi da izbrises:
1) /assets/css/node_modules
2) /assets/css/package-lock.json
Zatim, da prekopiras .prettierrc u root folder
Nakon toga iz root foldera pokrenes `npm install --save-dev --save-exact prettier`
I na kraju komitujes i composer.json i composer.lock (iz root foldera)

Ako mozes to danas bilo bi super, da bi pokrenuli Vercel build koji sada puca!

2021-10-04 18:59 UTC, vmladenovic approved these changes
Jedino pazi da iduci put ne komitujes `node_modules`

2021-10-04 19:00 UTC, merged